### ISSUE TITLE
Data retention

### ISSUE THREAD

**Issue by sashank** [stratosphereips/StratosphereLinuxIPS#1]
Any idea what is minimum number of network streams should be retained in practical deployments ?  For example currently I see that Argus output is being used as input for SLIPS.py .  

What is minimum duration or number of streams that argus should capture for SLIPS.py to start detecting attacks ?  What is the maximum duration the streams should be retained ? 

These parameters define whether it could be run inline mode ? or streams should be exported to offline server

**Comment by eldraco** [comment]
Hi
Right now the argus configuration in slips if forcing argus to __report__ the flows once every hour. This means that you must wait at least one hour to have some flows when you first execute it. But you only wait the first hour.

We need this initial waiting because in slips we need the __complete__ flows for the processing and also we need the real __time__ between flows. If we allow argus (or other Netflow programa for that matter) to give us the flows in a shorter time (usually 5 seconds to 5 minutes) then the timing between flows is not real; and the flows reported are not complete[1]. So we decided to wait and have the best information.

The normal flow sensor reports faster, but it does not report complete flows, and more importantly does not report inter-flow timing. This feature of inter-flow is very important for slips.

So the minimum duration that you must wait is 1 hour at the beginning. After that argus reports almost constantly and in real-time. Not sure how argus is doing this, but if you let it run, you will see that the flows come almost instantly later.

The minimum number of flows needed by slips to report something meaningful is 3, because we want a letter for the periodicity. If you _don't_ use the detection models and you only want to see the letters (cat file.binetflow | ./slips.py -D | less -R) you can see even connections with 1 flow. But there is no enough information for a good detection.

Yes, to be run in inline mode, I suggest argus with 1 hour report time (-S 3600 or use our conf) and slips with a time window of 5 minutes and detection models. Like this (assuming you are in the slips folder) (sudo is only for argus, you can run it in another console):

sudo argus -F argus.conf -i eth0 -w - | ra -n -Z b -F ra.conf -r - | ./slips.py -w 5 -f models -D   

If you want to speed up the analysis a little you can use a time window of 1 minute (-w 1).


[1] Sensors are doing this by reporting an incomplete flow ever X time. And then is up to the collector to try to put them together. However this task can be impossible given how networks work, and also we lost the real inter-flow time. Not to mention that the flows can get out of order and we can not allow that.

Hope it helps

**Comment by sashank** [comment]
Ok. Thanks for the information. I will dig deeper into it.
Few side questions
1. What are the flow sensors you mentioned (any reference ?)
2. Is there any difference between NetFlow and Argus output ? In other words Can we use NetFlow records  with slips.py with not much effort ?

**Comment by eldraco** [comment]
1. With sensors I mean the Exporters in Netflow terminology, the ones in charge of reading the packets from the network.

2. Yes, there are some significant differences (depending on argus conf also), but the most important is that Argus flows are bidirectional. Which is very nice since the analyst don't have to try to get the flows together.

I think that it may be possible to use NetFlows with slips. But we need to do some task, at least:
- Reconstruct the bidirectional flows the best you can. (this can be impossible in some situations)
- Research again and retrain the slips models to adjust the thresholds for Netflows. Also verify the results with experiments to be sure is working fine.
It should not be impossible to do it!
