### ISSUE TITLE
ML Train

### ISSUE THREAD

**Issue by aysesarii** [stratosphereips/StratosphereLinuxIPS#116]
Hi Dev,

I want to train the model with another dataset. However, I could not find in which module you separated the training and test data.  Training score is always 1.0. I couldn't understand what purpose the flowmldetection.py, lstm-cc-detection-1.py and rnn_model.py files were written for.  I tried using the flowmldetection.py file but without success.
I will be grateful if you could help me.

Thanks :)

**Comment by eldraco** [comment]
Hi Aysesarii.
Did you check the documentation here? https://stratospherelinuxips.readthedocs.io/en/develop/training.html
It is not super extensive, but it should keep you moving in the training.

All the training and testing is done by Slips, you just have to modify the configuration to add 'train', and the label, and then give Slips whatever data you want.

I hope to make some video about this later.

**Comment by aysesarii** [comment]
Hi Eldraco thank you for answering,
I read the document you mentioned and followed the steps as you stated. However, I get an output like this:
"[flowmldetection] Training Score: 1.0"
When I examined the flowmldetection.py file, I saw that the entire data set was given to the model without separating it as training and test data. This part confused me. Shouldn't the dataset be split into 80% - 20% (train_data and test_data)?

**Comment by eldraco** [comment]
You don't have to separate the data in training and testing. Since slips is not designed to evaluate the performance of models like a Ml framework. Slips is designed to use it. So
1- You put Slips in train mode
2- You tell slips which label you are gonna give it (normal or malicious)
3- You give slips this traffic and it learns from it
4- You give another label (normal or malicious)
5- You give Slips this new traffic and it extends the previous learning model with this
6- You continue doing this, showing Slips was is 'normal' and 'malicious' for you.
7- You put Slips in test mode (maybe the name is not the best honestly)
8- You use the model you just trained for real detections.
How good or bad the model will be is now up to your traffic and how many times the traffic was seen
More clear?

**Comment by aysesarii** [comment]
Yes, I understand better, thank you very much.
But how did you choose the model without using a performance metric? For example how did you choose SGDclassifier ?

**Comment by eldraco** [comment]
Hi Aysesarii. Sorry for the delay.
The model that is shipped with Slips, was chosen in this way:
1- Only a small set of models support online learning, so there were not many options. From these, SGDClassifier with SVM was chosen because of its better performance explained here
2- We used 10 botnet infections and 10 normal traffic from our networks. These were split in 80%/20% (16 and 4) for a small training/cross validation and testing.  We cross validate some parameters
3- We chose the model parameters that performed best in the testing
4- The model is published

However, if you train your model locally, this is completely up to you. The best idea would be to 'extend' the Slips model with your normal traffic probably, so you retrain it

**Comment by souravs17031999** [comment]
@eldraco what was the dataset used for the training ? is it some open source data or in house which slips used ?

**Comment by eldraco** [comment]
All our datasets are open and freely published. See here https://mcfp.felk.cvut.cz/publicDatasets/
In particular the datasets used where the ones from IoT-23 dataset, and Android mishief dataset.
However, it is not as simple as to pick a dataset and thats it. The dataset has to have many characterisitcs we need, like tuples, CC channels, benign data, etc, etc. 

Also in the ML flow detection, you can train with your own data at home. 

Did it helped?

**Comment by souravs17031999** [comment]
yes, thanks @eldraco. I will try out what you suggested.
One have one question though, since IoT-23 dataset would be traffic generated from IoT devices and I want to have some use case for real time traffic generated via internet (HTTP, HTTPS protocols) , will it help there ?

**Comment by eldraco** [comment]
Sorry for the delay @souravs17031999 . 
IoT-23 has internet traffic with those protocols. So it should work somehow
