### ISSUE TITLE
Adding "community_id" in the alert.json output

### ISSUE THREAD

**Issue by SarahAlh** [stratosphereips/StratosphereLinuxIPS#212]
**Describe:**
It would be ideal if (alert.json) output has a `community_id` to enable correlation of network events related to a single flow in ELK.

Another option would be to have additional fields in JSON file  for `destination_ip` and `destination_port`, so that it is easy to ship to ELK using community ID processor. 

**Example:**
`{ "Format": "IDEA0", "ID": "d22b17e5-e076-488c-a8a3-b88cbbfee769", "DetectTime": "2023-01-31T14:40:53.907485+00:00", "EventTime": "2023-01-31T14:40:53.907512+00:00", "Category": ["Anomaly.Connection"], "Confidence": 1, **"Source": [{"IP4": ["192.168.1.132"], "Port": [49385], "Proto": ["udp"]}]**, "Attach": [{"Content": "Connection to unknown destination port 49385/UDP destination IP 192.168.1.129. ", "ContentType": "text/plain"}] }`

By adding the following on the JSON output:
`"Destination": [{"IP4": ["192.168.1.129"], "Port": [49385], "Proto": ["udp"]}]`

It is easy to implement the following to have the `community_id` in ELK using the ingest pipelines, community ID processor:
```
[
  {
    "community_id": {
      "source_ip": "Source.IP4",
      "source_port": "Source.port",
      "destination_ip": "Destination.IP4",
      "destination_port": "Destination.Port",
      "iana_number": "Proto",
      "target_field": "community_id"
    }
  }
]
```

**Comment by eldraco** [comment]
Hi @SarahAlh, thanks for the feature request.
We decided to do the following to allow you to add the community_id.

1. In the alerts.json file, currently there is already a field "Source" that it is the source IP; a field "Target" that it is the destination IP; Port that is the destination port and Proto. So you can use these to build your community_id. The reason why they are called 'Source' and 'Target' and not 'source ip' and 'destination ip' is that the evidence of attack and its direction doesn't have to match the origin of the packet. 
Example of current json 
`{ "Format": "IDEA0", "ID": "8bf09497-25a9-4536-b00a-90f951e55171", "DetectTime": "2022-08-25T13:18:20.477898+00:00", "EventTime": "2022-08-25T13:18:20.477908+00:00", "Category": ["Anomaly.Connection"], "Confidence": 1, "Source": [{"IP4": ["192.168.1.2"]}], "Target": [{"IP4": ["41.238.140.185"], "Port": [53294], "Proto": ["tcp"]}], "Attach": [{"Content": "Connection to unknown destination port 53294/TCP destination IP 41.238.140.185. ", "ContentType": "text/plain"}] }`

2. Anyway we will add the UID of the Zeek flows to each evidence in the alert.json file. So you can directly find the correct flows that generated the evidence. Please see that there are usually many flows related with the generation of an evidence, for example in a port scan.

3. We will add a new type of line in the alert.json with the "Alert" in the sense of the request for blocking. This is because in slips the hierarchy an Alert is composed of many Evidences and one Evidence is composed of many Flows.

**Comment by AlyaGomaa** [comment]
Hello @SarahAlh 

We are done adding the 'uids' field to each evidence in our alerts.json

Also slips alerts are now logged in alerts.json, with the ```Category``` field set to ```Alert```  and the description of the alert in the ```Content``` field

Here's an example an alert from alerts.json:

> { "Format": "Json", "ID": "7134c0f1-b8fb-4eee-a89f-260446da41c0", "DetectTime": "2023-02-16T18:21:18.102767+00:00", "EventTime": "2023-02-16T18:21:18.102804+00:00", "Category": "Alert", "Confidence": 1, "Source": [{"IP4": ["216.245.221.83"], "Type": ["Phishing honeypot"]}], "Attach": [{"Content": "2021-06-07T05:07:39.086198+02:00: Src IP 216.245.221.83            . Generated an alert given enough evidence on timewindow 10. (real time 2023/02/16 20:21:18.127345)", "ContentType": "text/plain"}], "uids": [] }

 
Changes are going to be merged to the master branch by the end of this month, you can use the develop branch if you want to use them earlier!

**Comment by AlyaGomaa** [comment]
Merged to master branch
