### ISSUE TITLE
docker hub docs issue :  hide-and-seek-short.pcap file is missing

### ISSUE THREAD

**Issue by Aman123lug** [stratosphereips/StratosphereLinuxIPS#238]
In docker hub docs there are some issue in : https://hub.docker.com/r/stratosphereips/slips -- hide-and-seek-short.pcap file is missing need to fix this - after 2 commands when you enter 3rd command it will through error : file not found [hide-and-seek-short.pcap] when we create this manually it works.

**Comment by eldraco** [comment]
Hi Aman123lug. Please, can you be more clear with the issue? Is this a problem of the documentation in docker hub? or in the git repository? 

I think the issue is in README of the branch that was used to upload the docker. 
@AlyaGomaa ?

Please see that there is a format to report issues that you must fill completely. If not we can not work on it because it is unclear. Do not skip the issue formating.
thanks
sebas
