### ISSUE TITLE
Building slips from dockerfile failed

### ISSUE THREAD

**Issue by lpp5139** [stratosphereips/StratosphereLinuxIPS#579]
**Describe the bug**
Unable to build slips on docker file. Failure seen at step 6 and 9 with error message "install/requriements.txt: No such file or directory". 
 
**To Reproduce**
1. Clone the git repo: git clone https://github.com/stratosphereips/StratosphereLinuxIPS.git
2. cd ~/StratosphereLinuxIPS/docker/ubunutu-image
3. Run command: docker build --no-cache -t slips -f Dockerfile .
4. An error appears at step 6 and 9. 

**Expected behavior**
Build should be successful without any errors, and install/requirements.txt file exists. 

**Screenshots**
WSL failure
![error_wsl](https://github.com/stratosphereips/StratosphereLinuxIPS/assets/60235793/c5dc419c-62b5-42d8-99fc-320132cc475f)

Windows failure
![error_windows](https://github.com/stratosphereips/StratosphereLinuxIPS/assets/60235793/22b4e302-79c9-4fba-ac60-70df7351f999)

**Branch**
Master and Develop both

**Environment (please complete the following information):**
 - OS: Windows 11/ WSL2 ubuntu
 - Version: Ubuntu version 20.04
 - Python version - 3.11.4 windows and 3.8.10 ubuntu WSL
 - Are you running slips in docker or locally? Docker
 - Docker version - 26.0.0
 - Slips docker image used : ubuntu-image

**Comment by AlyaGomaa** [comment]
Hello @lpp5139 

i think the issue is that you're building the docker image from this dir

~/StratosphereLinuxIPS/docker/ubunutu-image

while you should build it from the slips main dir
1. ~/StratosphereLinuxIPS/
2. docker build --no-cache -t slips -f Dockerfile .

so that docker can find the install/requirement.txt in the . context.

Let me know if you need any help, and let me know if it works :)

also remember that you can just pull the docker image instead of manually building it using
`docker pull stratosphereips/slips:latest`

**Comment by lpp5139** [comment]
Hey @AlyaGomaa, thanks for getting back. Following steps helped me out. I tested it in windows WSL
 

1. cd ~/StratosphereLinuxIPS
2.  docker build --no-cache -t slips -f docker/ubuntu-image/Dockerfile .
3. docker run -it --rm --net=host slips(creating a dataset storage using -v removes the existing file from dataset folder).
4. vim slips.py
5. :set ff=unix
6. :wq
7. ./slips.py -c config/slips.conf -f dataset/test3-mixed.binetflow

Step 4-6 is performed because of line ending characters. Files are created or edited or cloned on a Windows system and uses Windows/DOS-style line endings (CR+LF), whereas Linux systems like Ubuntu require Unix-style line endings (LF).

Can the installation guide be updated to include steps 1 and 2?
